Retail Analytics: Predicting Customer Purchase Behavior

Business Introduction:
Welcome to RetailVC's Retail Analytics Solutions, a leading provider of data-driven solutions for retail businesses. RetailVC specializes in using advanced analytics techniques to help retailers optimize their operations, enhance customer experiences, and drive business growth. Its mission is to empower retail organizations with actionable insights that enable them to make informed decisions, improve performance, and remain competitive in today's dynamic marketplace.

Problem Statement:
The goal of this capstone project is to develop a comprehensive understanding of customer behavior and preferences based on retail transaction data. The aim is to analyze customers' demographic information, purchasing patterns, and interactions with marketing campaigns to identify key insights. These insights will inform strategic decision-making and drive business growth. Specifically, the focus will be on predicting customers' responses to marketing campaigns and optimizing promotional strategies to maximize their effectiveness and return on investment (ROI).

Python tasks:
- Exploratory Data Analysis

General Data Overview:
- Check the first few rows of the dataset to understand its structure
- Check the data types of each column
- Check for any missing values in the dataset
  
Descriptive Statistics:
- statistical summary for numerical features using dataset from sql csv file
- Compute summary statistics for numerical columns (mean, median, min, max, and standard deviation)
- Explore the distribution of numerical variables using histograms or box plots


TABLEAU TASKS

Univariate Analysis:
- Explore the distribution of each numerical variable using histograms 
- Explore the distribution of each categorical variable using bar plots 
- Identify outliers in numerical variables using box plots or scatter plots
  
Bivariate Analysis:
- Explore the relationship between numerical variables and the target variable (Response) using scatter plots or correlation matrices
- Explore the relationship between categorical variables and the target variable using bar plots or chi-square tests
- Explore the relationship between numerical and categorical variables using box plots 
  
Observations: Write an analysis report on performing exploratory data analysis (EDA) using Python in the context of building a fraud detection system for Retail Analytics

### ACTION: LOAD NECESSARY LIBRARIES

In [5]:
pip install seaborn

Requirement already satisfied: seaborn in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from seaborn) (2.4.3)
Requirement already satisfied: pandas>=1.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from seaborn) (3.0.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Requirement already satisfied: pyparsing>=3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [6]:
pip install plotly

Requirement already satisfied: plotly in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (6.6.0)
Requirement already satisfied: narwhals>=1.15.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from plotly) (2.19.0)
Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from plotly) (26.0)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [7]:
pip install bokeh

Requirement already satisfied: bokeh in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.9.0)
Requirement already satisfied: Jinja2>=2.9 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from bokeh) (3.1.6)
Requirement already satisfied: contourpy>=1.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from bokeh) (1.3.3)
Requirement already satisfied: narwhals>=1.13 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from bokeh) (2.19.0)
Requirement already satisfied: numpy>=1.16 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from bokeh) (2.4.3)
Requirement already satisfied: packaging>=16.8 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from bokeh) (26.0)
Requirement already satisfied: pillow>=7.1.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from bokeh) (12.1.1)
Requirement already satisfied: PyYAML>=3.10 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from bokeh) (6.0.3)
Requirement already satisfied: tornado>=6.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from bokeh) (6.5.5)
Requirement already satisfied: xyzservices>=2021.09.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from bokeh) (2026.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from Jinja2>=2.9->bokeh) (3.0.3)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [8]:
pip install voila

Requirement already satisfied: voila in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (0.5.11)
Requirement already satisfied: jupyter-client<9,>=7.4.4 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from voila) (8.8.0)
Requirement already satisfied: jupyter-core>=4.11.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from voila) (5.9.1)
Requirement already satisfied: jupyter-server<3,>=1.18 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from voila) (2.17.0)
Requirement already satisfied: jupyterlab-server<3,>=2.3.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from voila) (2.28.0)
Requirement already satisfied: nbclient>=0.4.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from voila) (0.10.4)
Requirement already satisfied: nbconvert<8,>=6.4.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from voila) (7.17.0)
Requirement already satisfied: traitlets<6,>=5.0.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from voila) (5.14.3)
Requirement already satisfied: websockets>=9.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from voila) (16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyter-client<9,>=7.4.4->voila) (2.9.0.post0)
Requirement already satisfied: pyzmq>=25.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyter-client<9,>=7.4.4->voila) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyter-client<9,>=7.4.4->voila) (6.5.5)
Requirement already satisfied: anyio>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyter-server<3,>=1.18->voila) (4.12.1)
Requirement already satisfied: argon2-cffi>=21.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyter-server<3,>=1.18->voila) (25.1.0)
Requirement already satisfied: jinja2>=3.0.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyter-server<3,>=1.18->voila) (3.1.6)
Requirement already satisfied: jupyter-events>=0.11.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyter-server<3,>=1.18->voila) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyter-server<3,>=1.18->voila) (0.5.4)
Requirement already satisfied: nbformat>=5.3.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyter-server<3,>=1.18->voila) (5.10.4)
Requirement already satisfied: packaging>=22.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyter-server<3,>=1.18->voila) (26.0)
Requirement already satisfied: prometheus-client>=0.9 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyter-server<3,>=1.18->voila) (0.24.1)
Requirement already satisfied: send2trash>=1.8.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyter-server<3,>=1.18->voila) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyter-server<3,>=1.18->voila) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyter-server<3,>=1.18->voila) (1.9.0)
Requirement already satisfied: babel>=2.10 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyterlab-server<3,>=2.3.0->voila) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyterlab-server<3,>=2.3.0->voila) (0.13.0)
Requirement already satisfied: jsonschema>=4.18.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyterlab-server<3,>=2.3.0->voila) (4.26.0)
Requirement already satisfied: requests>=2.31 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyterlab-server<3,>=2.3.0->voila) (2.32.5)
Requirement already satisfied: beautifulsoup4 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from nbconvert<8,>=6.4.5->voila) (4.14.3)
Requirement already satisfied: bleach!=5.0.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from bleach[css]!=5.0.0->nbconvert<8,>=6.4.5->voila) (6.3.0)
Requirement already satisfied: defusedxml in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from nbconvert<8,>=6.4.5->voila) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from nbconvert<8,>=6.4.5->voila) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from nbconvert<8,>=6.4.5->voila) (3.0.3)
Requirement already satisfied: mistune<4,>=2.0.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from nbconvert<8,>=6.4.5->voila) (3.2.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from nbconvert<8,>=6.4.5->voila) (1.5.1)
Requirement already satisfied: pygments>=2.4.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from nbconvert<8,>=6.4.5->voila) (2.19.2)
Requirement already satisfied: idna>=2.8 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from anyio>=3.1.0->jupyter-server<3,>=1.18->voila) (3.11)
Requirement already satisfied: argon2-cffi-bindings in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=1.18->voila) (25.1.0)
Requirement already satisfied: webencodings in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert<8,>=6.4.5->voila) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from bleach[css]!=5.0.0->nbconvert<8,>=6.4.5->voila) (1.4.0)
Requirement already satisfied: attrs>=22.2.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.3.0->voila) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.3.0->voila) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.3.0->voila) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.3.0->voila) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyter-core>=4.11.0->voila) (4.9.4)
Requirement already satisfied: python-json-logger>=2.0.4 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=1.18->voila) (4.0.0)
Requirement already satisfied: pyyaml>=5.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=1.18->voila) (6.0.3)
Requirement already satisfied: rfc3339-validator in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=1.18->voila) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=1.18->voila) (0.1.1)
Requirement already satisfied: fqdn in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.18->voila) (1.5.1)
Requirement already satisfied: isoduration in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.18->voila) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.18->voila) (3.0.0)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.18->voila) (1.1.0)
Requirement already satisfied: uri-template in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.18->voila) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.18->voila) (25.10.0)
Requirement already satisfied: fastjsonschema>=2.15 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from nbformat>=5.3.0->jupyter-server<3,>=1.18->voila) (2.21.2)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from python-dateutil>=2.8.2->jupyter-client<9,>=7.4.4->voila) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.3.0->voila) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.3.0->voila) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.3.0->voila) (2026.2.25)
Requirement already satisfied: lark>=1.2.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.18->voila) (1.3.1)
Requirement already satisfied: ptyprocess in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from terminado>=0.8.3->jupyter-server<3,>=1.18->voila) (0.7.0)
Requirement already satisfied: cffi>=2.0.0b1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=1.18->voila) (2.0.0)
Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from cffi>=2.0.0b1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=1.18->voila) (3.0)
Requirement already satisfied: soupsieve>=1.6.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from beautifulsoup4->nbconvert<8,>=6.4.5->voila) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from beautifulsoup4->nbconvert<8,>=6.4.5->voila) (4.15.0)
Requirement already satisfied: arrow>=0.15.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.18->voila) (1.4.0)
Requirement already satisfied: tzdata in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.18->voila) (2025.3)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [9]:
pip install pandasql

Requirement already satisfied: pandasql in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (0.7.3)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandasql) (2.4.3)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandasql) (3.0.1)
Requirement already satisfied: sqlalchemy in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandasql) (2.0.49)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Requirement already satisfied: greenlet>=1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from sqlalchemy->pandasql) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from sqlalchemy->pandasql) (4.15.0)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [10]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import psycopg2
from pandasql import sqldf
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
pd.options.plotting.backend = 'plotly'
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
import voila
import warnings
warnings.filterwarnings('ignore')

### ACTION: DATA EXPLORATION

In [13]:
#importing csv data into python
#store it as a dataframe df
df = pd.read_csv('marketingcmp_sqlcsv copy 2.csv')
df

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Age,Age_Group,...,AcceptedCmp4,AcceptedCmp5,Response,Response_Total,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Z_CostContact,Z_Revenue
0,0,1985,Graduation,Married,"$70,951.00",0,0,4/5/13,41,36-45,...,0,0,0,0,3,4,9,1,NaN,NaN
1,1,1961,Graduation,Single,"$57,091.00",0,0,6/15/14,65,56+,...,0,0,1,2,7,3,7,5,NaN,NaN
2,9,1975,Master,Single,"$46,098.00",1,1,8/18/12,51,46-55,...,0,0,0,0,3,2,2,8,NaN,NaN
3,13,1947,PhD,Widow,"$25,358.00",0,1,7/22/13,79,56+,...,0,0,0,0,1,0,3,6,NaN,NaN
4,17,1971,PhD,Married,"$60,491.00",0,1,6/9/13,55,46-55,...,0,0,0,0,6,11,7,5,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2231,11178,1972,Master,Single,"$42,394.00",1,0,3/23/14,54,46-55,...,0,0,0,0,1,0,3,7,NaN,NaN
2232,11181,1949,PhD,Married,"$156,924.00",0,0,8/29/13,77,56+,...,0,0,0,0,0,0,0,0,NaN,NaN
2233,11187,1978,Basic,Single,"$26,487.00",1,0,5/20/13,48,46-55,...,0,0,0,0,2,1,3,5,NaN,NaN
2234,11188,1957,Graduation,Together,"$26,091.00",1,1,2/25/14,69,56+,...,0,0,0,0,2,1,3,5,NaN,NaN
2235,11191,1986,Graduation,Divorced,"$41,411.00",0,0,7/12/13,40,36-45,...,0,0,0,0,2,1,4,6,NaN,NaN

In [14]:
#make a copy of the df to protect the og for any changes and updates
dfcopy = df.copy()
dfcopy

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Age,Age_Group,...,AcceptedCmp4,AcceptedCmp5,Response,Response_Total,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Z_CostContact,Z_Revenue
0,0,1985,Graduation,Married,"$70,951.00",0,0,4/5/13,41,36-45,...,0,0,0,0,3,4,9,1,NaN,NaN
1,1,1961,Graduation,Single,"$57,091.00",0,0,6/15/14,65,56+,...,0,0,1,2,7,3,7,5,NaN,NaN
2,9,1975,Master,Single,"$46,098.00",1,1,8/18/12,51,46-55,...,0,0,0,0,3,2,2,8,NaN,NaN
3,13,1947,PhD,Widow,"$25,358.00",0,1,7/22/13,79,56+,...,0,0,0,0,1,0,3,6,NaN,NaN
4,17,1971,PhD,Married,"$60,491.00",0,1,6/9/13,55,46-55,...,0,0,0,0,6,11,7,5,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2231,11178,1972,Master,Single,"$42,394.00",1,0,3/23/14,54,46-55,...,0,0,0,0,1,0,3,7,NaN,NaN
2232,11181,1949,PhD,Married,"$156,924.00",0,0,8/29/13,77,56+,...,0,0,0,0,0,0,0,0,NaN,NaN
2233,11187,1978,Basic,Single,"$26,487.00",1,0,5/20/13,48,46-55,...,0,0,0,0,2,1,3,5,NaN,NaN
2234,11188,1957,Graduation,Together,"$26,091.00",1,1,2/25/14,69,56+,...,0,0,0,0,2,1,3,5,NaN,NaN
2235,11191,1986,Graduation,Divorced,"$41,411.00",0,0,7/12/13,40,36-45,...,0,0,0,0,2,1,4,6,NaN,NaN

In [19]:
# Check the first few rows of the dataset to understand its structure
dfcopy.shape

(2236, 32)

In [20]:
dfcopy.head(10)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Age,Age_Group,...,AcceptedCmp4,AcceptedCmp5,Response,Response_Total,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Z_CostContact,Z_Revenue
0,0,1985,Graduation,Married,"$70,951.00",0,0,4/5/13,41,36-45,...,0,0,0,0,3,4,9,1,NaN,NaN
1,1,1961,Graduation,Single,"$57,091.00",0,0,6/15/14,65,56+,...,0,0,1,2,7,3,7,5,NaN,NaN
2,9,1975,Master,Single,"$46,098.00",1,1,8/18/12,51,46-55,...,0,0,0,0,3,2,2,8,NaN,NaN
3,13,1947,PhD,Widow,"$25,358.00",0,1,7/22/13,79,56+,...,0,0,0,0,1,0,3,6,NaN,NaN
4,17,1971,PhD,Married,"$60,491.00",0,1,6/9/13,55,46-55,...,0,0,0,0,6,11,7,5,NaN,NaN
5,20,1965,2n Cycle,Married,"$46,891.00",0,1,1/9/13,61,56+,...,0,0,0,0,2,1,4,4,NaN,NaN
6,22,1976,Graduation,Divorced,"$46,310.00",1,0,3/12/12,50,46-55,...,0,0,0,0,6,1,5,8,NaN,NaN
7,24,1960,Master,Together,"$17,144.00",1,1,2/15/14,66,56+,...,0,0,0,0,3,0,4,7,NaN,NaN
8,25,1958,Graduation,Married,"$65,148.00",0,1,11/16/12,68,56+,...,0,0,0,0,6,6,7,4,NaN,NaN
9,35,1987,Graduation,Married,"$25,545.00",1,0,8/9/12,39,36-45,...,0,0,1,1,2,2,3,6,NaN,NaN

In [21]:
dfcopy.tail(10)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Age,Age_Group,...,AcceptedCmp4,AcceptedCmp5,Response,Response_Total,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Z_CostContact,Z_Revenue
2226,11121,1981,Graduation,Married,"$19,419.00",1,0,10/11/12,45,36-45,...,0,0,0,0,4,0,3,9,NaN,NaN
2227,11148,1975,Graduation,Together,"$22,280.00",1,0,5/19/13,51,46-55,...,0,0,0,0,1,0,2,8,NaN,NaN
2228,11166,1961,Graduation,Married,"$49,678.00",0,1,2/2/13,65,56+,...,0,0,0,0,6,2,4,7,NaN,NaN
2229,11171,1965,Master,Married,"$56,962.00",2,1,11/10/13,61,56+,...,0,0,0,0,6,3,5,7,NaN,NaN
2230,11176,1970,PhD,Together,"$65,968.00",0,1,12/5/14,56,56+,...,0,0,0,0,5,4,7,3,NaN,NaN
2231,11178,1972,Master,Single,"$42,394.00",1,0,3/23/14,54,46-55,...,0,0,0,0,1,0,3,7,NaN,NaN
2232,11181,1949,PhD,Married,"$156,924.00",0,0,8/29/13,77,56+,...,0,0,0,0,0,0,0,0,NaN,NaN
2233,11187,1978,Basic,Single,"$26,487.00",1,0,5/20/13,48,46-55,...,0,0,0,0,2,1,3,5,NaN,NaN
2234,11188,1957,Graduation,Together,"$26,091.00",1,1,2/25/14,69,56+,...,0,0,0,0,2,1,3,5,NaN,NaN
2235,11191,1986,Graduation,Divorced,"$41,411.00",0,0,7/12/13,40,36-45,...,0,0,0,0,2,1,4,6,NaN,NaN

In [23]:
# Check the data types of each column
dfcopy.dtypes
#integer is sql equivalent to integer
#str is sql equivalent to varchar
#float is sql equivalent to decimal

ID                       int64
Year_Birth               int64
Education                  str
Marital_Status             str
Income                     str
Kidhome                  int64
Teenhome                 int64
Dt_Customer                str
Age                      int64
Age_Group                  str
Recency                  int64
Complain                 int64
MntWines                 int64
MntFruits                int64
MntMeatProducts          int64
MntFishProducts          int64
MntSweetProducts         int64
MntGoldProds             int64
NumDealsPurchases        int64
AcceptedCmp1             int64
AcceptedCmp2             int64
AcceptedCmp3             int64
AcceptedCmp4             int64
AcceptedCmp5             int64
Response                 int64
Response_Total           int64
NumWebPurchases          int64
NumCatalogPurchases      int64
NumStorePurchases        int64
NumWebVisitsMonth        int64
Z_CostContact          float64
Z_Revenue              float64
dtype: object

In [25]:
# Check for any missing values in the dataset
dfcopy.isnull().sum()

#income has 24 nulls/missing values-tells me that there are 24 customers that have no income
#z_costcontact an z_revenue are empty columns

ID                        0
Year_Birth                0
Education                 0
Marital_Status            0
Income                   24
Kidhome                   0
Teenhome                  0
Dt_Customer               0
Age                       0
Age_Group                 0
Recency                   0
Complain                  0
MntWines                  0
MntFruits                 0
MntMeatProducts           0
MntFishProducts           0
MntSweetProducts          0
MntGoldProds              0
NumDealsPurchases         0
AcceptedCmp1              0
AcceptedCmp2              0
AcceptedCmp3              0
AcceptedCmp4              0
AcceptedCmp5              0
Response                  0
Response_Total            0
NumWebPurchases           0
NumCatalogPurchases       0
NumStorePurchases         0
NumWebVisitsMonth         0
Z_CostContact          2236
Z_Revenue              2236
dtype: int64

### Descriptive Statistics:

### ACTION: Statistical summary for numerical features using dataset

In [62]:
#Descriptive Statistics (Describe)
dfcopy.describe()

,ID,Year_Birth,Kidhome,Teenhome,Age,Recency,Complain,MntWines,MntFruits,MntMeatProducts,...,AcceptedCmp4,AcceptedCmp5,Response,Response_Total,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Z_CostContact,Z_Revenue
count,2236.000000,2236.000000,2236.000000,2236.000000,2236.000000,2236.000000,2236.000000,2236.000000,2236.000000,2236.000000,...,2236.000000,2236.000000,2236.000000,2236.000000,2236.000000,2236.000000,2236.000000,2236.000000,0.0,0.0
mean,5591.551878,1968.796512,0.444991,0.506261,57.203488,49.147138,0.009392,303.873435,26.271020,166.924419,...,0.074687,0.072451,0.148479,0.445886,4.082737,2.659213,5.789356,5.317531,NaN,NaN
std,3245.240106,11.980604,0.538551,0.544615,11.980604,28.954880,0.096477,336.876776,39.761356,225.778550,...,0.262944,0.259291,0.355654,0.889524,2.779736,2.920752,3.253756,2.424756,NaN,NaN
min,0.000000,1893.000000,0.000000,0.000000,30.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
25%,2828.250000,1959.000000,0.000000,0.000000,49.000000,24.000000,0.000000,23.000000,1.000000,16.000000,...,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,3.000000,3.000000,NaN,NaN
50%,5458.500000,1970.000000,0.000000,0.000000,56.000000,49.000000,0.000000,173.000000,8.000000,67.000000,...,0.000000,0.000000,0.000000,0.000000,4.000000,2.000000,5.000000,6.000000,NaN,NaN
75%,8427.750000,1977.000000,1.000000,1.000000,67.000000,74.000000,0.000000,505.000000,33.000000,232.000000,...,0.000000,0.000000,0.000000,1.000000,6.000000,4.000000,8.000000,7.000000,NaN,NaN
max,11191.000000,1996.000000,2.000000,2.000000,133.000000,99.000000,1.000000,1493.000000,199.000000,1725.000000,...,1.000000,1.000000,1.000000,5.000000,27.000000,28.000000,13.000000,20.000000,NaN,NaN

In [36]:
dfcopy.head(5)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Age,Age_Group,...,AcceptedCmp4,AcceptedCmp5,Response,Response_Total,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Z_CostContact,Z_Revenue
0,0,1985,Graduation,Married,"$70,951.00",0,0,4/5/13,41,36-45,...,0,0,0,0,3,4,9,1,NaN,NaN
1,1,1961,Graduation,Single,"$57,091.00",0,0,6/15/14,65,56+,...,0,0,1,2,7,3,7,5,NaN,NaN
2,9,1975,Master,Single,"$46,098.00",1,1,8/18/12,51,46-55,...,0,0,0,0,3,2,2,8,NaN,NaN
3,13,1947,PhD,Widow,"$25,358.00",0,1,7/22/13,79,56+,...,0,0,0,0,1,0,3,6,NaN,NaN
4,17,1971,PhD,Married,"$60,491.00",0,1,6/9/13,55,46-55,...,0,0,0,0,6,11,7,5,NaN,NaN

In [51]:
import pandas as pd

In [54]:
# Clean Income column - remove $ and commas
# changing INCOME column which was originally a string to a float so that i can run a statistical summary 
df['Income'] = df['Income'].replace('[\$,]', '', regex=True).astype(float)

In [57]:
#choosing the specific columns i want to use for statistics(columns with numbers)
#selecting only numerical columns
num_cols = ['Year_Birth', 'Income', 'Kidhome', 'Teenhome', 'Age',
            'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases',
            'NumWebVisitsMonth', 'Response_Total']
num_cols

['Year_Birth',
 'Income',
 'Kidhome',
 'Teenhome',
 'Age',
 'NumWebPurchases',
 'NumCatalogPurchases',
 'NumStorePurchases',
 'NumWebVisitsMonth',
 'Response_Total']

In [63]:
# See the data type of each column
print(df[num_cols].dtypes)

Year_Birth               int64
Income                 float64
Kidhome                  int64
Teenhome                 int64
Age                      int64
NumWebPurchases          int64
NumCatalogPurchases      int64
NumStorePurchases        int64
NumWebVisitsMonth        int64
Response_Total           int64
dtype: object

In [59]:
# Cleaning the Income column - remove $ and commas, then fill NaN with 0 or drop
df['Income'] = df['Income'].replace('[\$,]', '', regex=True)
df['Income'] = pd.to_numeric(df['Income'], errors='coerce')

In [61]:
#verifying the updated datatype of INCOME
print(df['Income'].dtype)   # should show float64
print(df['Income'].head())  # should show numbers without $

float64
0    70951.0
1    57091.0
2    46098.0
3    25358.0
4    60491.0
Name: Income, dtype: float64

In [60]:
#stats summary
#.T switches the rows and columns so that I can have the columns at the left.
stsum = df[num_cols].describe().T
stsum['Median']   = df[num_cols].median(numeric_only=True)
stsum['Skewness'] = df[num_cols].skew(numeric_only=True)

stsum

,count,mean,std,min,25%,50%,75%,max,Median,Skewness
Year_Birth,2236.0,1968.796512,11.980604,1893.0,1959.0,1970.0,1977.0,1996.0,1970.0,-0.351844
Income,2212.0,52232.510850,25187.455359,1730.0,35233.5,51381.5,68522.0,666666.0,51381.5,6.765274
Kidhome,2236.0,0.444991,0.538551,0.0,0.0,0.0,1.0,2.0,0.0,0.632458
Teenhome,2236.0,0.506261,0.544615,0.0,0.0,0.0,1.0,2.0,0.0,0.407663
Age,2236.0,57.203488,11.980604,30.0,49.0,56.0,67.0,133.0,56.0,0.351844
NumWebPurchases,2236.0,4.082737,2.779736,0.0,2.0,4.0,6.0,27.0,4.0,1.384989
NumCatalogPurchases,2236.0,2.659213,2.920752,0.0,0.0,2.0,4.0,28.0,2.0,1.884662
NumStorePurchases,2236.0,5.789356,3.253756,0.0,3.0,5.0,8.0,13.0,5.0,0.702418
NumWebVisitsMonth,2236.0,5.317531,2.424756,0.0,3.0,6.0,7.0,20.0,6.0,0.209989
Response_Total,2236.0,0.445886,0.889524,0.0,0.0,0.0,1.0,5.0,0.0,2.446563

### Exporting this statistical summary table

In [64]:
#excel file
stsum.to_excel('statistical_summary.xlsx', index=True)

In [65]:
#csv file
stsum.to_csv('statistical_summary.csv', index=True)

In [68]:
#verify where it was saved
import os
print(os.getcwd())

/Users/inigoarboleda/Python